version: '3.5'

services:
  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3500:3500'
    volumes:
      - uploads:/app/uploads

    links:
      - mongodb
    environment:
      DATABASE_USER: root
      DATABASE_PASS: password
      DATABASE_NAME: coding-challenge

  mongodb:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: coding-challenge

    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - '8081:8081'

networks:
  coding_challenge_network:
    driver: bridge

volumes:
  mongodb:
  uploads:
