name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./../../Dockerfile
          push: true
          tags: |
            aichalouraghi/coding-challenge:latest

      - name: Deploy with Docker Compose
        run: docker-compose up -d
